# Generated by Django 6.0.3 on 2026-04-07 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ALQUILADA', 'Alquilada'), ('MANTENIMIENTO', 'En Mantenimiento')], default='DISPONIBLE', max_length=20)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('inquilino_nombre', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquilino_nombre', models.CharField(max_length=150)),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_limite', models.DateField()),
                ('metodo_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ATRASADO', 'Atrasado')], default='PENDIENTE', max_length=20)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.propiedad')),
            ],
        ),
    ]
