# Generated by Django 6.0.3 on 2026-04-11 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_propiedadimagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('INQUILINO', 'Usuario de la casa')], default='INQUILINO', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.propiedad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles de usuario',
            },
        ),
        migrations.CreateModel(
            name='SolicitudSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('FUGA_AGUA', 'Fuga de agua'), ('ELECTRICO', 'Problema electrico'), ('HUMEDAD', 'Humedad o filtracion'), ('CERRADURA', 'Puerta o cerradura'), ('GAS', 'Gas u olor extrano'), ('ELECTRODOMESTICO', 'Electrodomestico'), ('OTRO', 'Otro dano')], default='OTRO', max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('EN_PROCESO', 'En proceso'), ('RESUELTA', 'Resuelta')], default='NUEVA', max_length=20)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_soporte', to='core.propiedad')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_soporte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud de soporte',
                'verbose_name_plural': 'solicitudes de soporte',
                'ordering': ['-creado_en'],
            },
        ),
    ]
