# Generated by Django 6.0.3 on 2026-04-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilusuario_solicitudsoporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='baños',
            field=models.PositiveIntegerField(default=0, help_text='Número de baños'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='habitaciones',
            field=models.PositiveIntegerField(default=0, help_text='Número de habitaciones'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='parquedero',
            field=models.BooleanField(default=False, help_text='¿Tiene parquedero?'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='patio',
            field=models.BooleanField(default=False, help_text='¿Tiene patio?'),
        ),
    ]
