# Generated by Django 6.0.3 on 2026-04-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_propiedad_baños_propiedad_habitaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta de Crédito'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], default='TRANSFERENCIA', max_length=20),
        ),
    ]
