# Generated by Django 6.0.3 on 2026-05-15 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contratomantenimiento_obligacionfiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalempleado',
            name='propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='core.propiedad'),
        ),
    ]
